config/routes.rb
Microtube::Application.routes.draw do
  resources :users, except: [:index]

  resources :user_sessions, only: [:new, :create, :destroy]
  get 'login', to: "user_sessions#new"
  delete 'logout', to: "user_sessions#destroy"

  resources :videos do
    resources :posts, only: :create
  end

  root to: "videos#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :video

  validates :message, :video, presence: true
  validates :name, length: { maximum: 20 }
  validates :message, length: { maximum: 500 }

  before_save :set_name

  private

  def set_name
    self.name = 'Anonymous' if self.name.empty?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic

  has_many :videos

  attr_readonly :login

  validates :login, length: 4..16
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  has_many :posts, dependent: :destroy

  has_attached_file :video, styles: { original: { } },
                            :path => ":rails_root/public/system/:attachment/:id/:style/:name_with_changed_extension",
                            :url => "/system/:attachment/:id/:style/:name_with_changed_extension",
                            processors: [:video_converter]

      Paperclip.interpolates :name_with_changed_extension do |attachment, style|
        attachment.instance.change_extension
      end

  validates :title, presence: true, length: 5..100
  validates :user, presence: true
  validates :description, length: { maximum: 1000 }
  validates_attachment_presence :video
  validates_attachment_content_type :video, content_type: /video/, message: "invalid"
  validates_attachment_size :video, less_than: 100.megabyte

  self.per_page = 5

  def change_extension
    File.basename(File.basename(self.video_file_name), File.extname(self.video_file_name)) + '.flv'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :logged_in?, :current_user

  def current_session
    UserSession.find
  end

  def current_user
    current_session.user
  end

  def logged_in?
    current_session != nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    params[:post][:video_id] = params[:video_id]
    @post = Post.new(params[:post])

    flash[:notice] = "Comment successfully created" if @post.save

    redirect_to @post.video
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])

    if @user_session.save
      redirect_to @user_session.user, notice: 'Successfully logged in'
    else
      render action: 'new'
    end
  end

  def destoy
    @user_session = current_session
    if @user_session
      @user_session.destroy
      flash[:notice] = 'Successfully logged out'
    end
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :own_only, only: [:edit, :update, :destroy]

  helper_method :own_account?

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to @user, notice: 'Profile was successfully created'
    else
      render action: 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'Profile was successfully updated'
    else
      render action: 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_url
  end

  private

  def own_only
    redirect_to(root_url, notice: "You can change only your own account") unless own_account?
  end

  def own_account?
    return false unless current_session
    params[:id] == current_user.id.to_s
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :has_upload_right, only: :new
  before_filter :own_only, only: [:edit, :update, :destroy]

  # GET /videos
  def index
    @videos = Video.page(params[:page]).order('created_at DESC')
  end

  # GET /videos/1
  def show
    @video = Video.find(params[:id])
    @post = Post.new
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  def create
    params[:video][:user_id] = current_user.id
    @video = Video.new(params[:video])

    if @video.save
      redirect_to @video, notice: 'Video was successfully created'
    else
      render action: "new"
    end
  end

  # PUT /videos/1
  def update
    @video = Video.find(params[:id])

    if @video.update_attributes(params[:video])
      redirect_to @video, notice: 'Video was successfully updated'
    else
      render action: "edit"
    end
  end

  # DELETE /videos/1
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    redirect_to current_user
  end

  private

  def has_upload_right
    redirect_to(root_url, :notice => "You must log in first.") unless logged_in?
  end

  def own_only
    redirect_to(root_url, :notice => "You can change only your own videos.") unless own_video?
  end

  def own_video?
    return false unless current_session
    Video.find(params[:id]).user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Microtube
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    #wrap
      #header
        #logo
          %h1= link_to 'Microtube', root_path
        #profile
          - if logged_in?
            %p
              You logged as
              = link_to current_user.login, current_user
            %p
              = link_to 'Edit Profile', edit_user_path(current_user)
              = link_to 'Log Out', logout_path, method: :delete
          - else
            = link_to 'Log In', login_path
            or
            = link_to 'Register', new_user_path
      .clear
      #main
        = yield

app/views/posts/_form.html.haml
= form_for [video, @post] do |f|
  -if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name, 'Имя'
    %br
    = f.text_field :name
  .field
    = f.label :message, 'Сообщение'
    %br
    = f.text_area :message, cols: 60, rows: 10
  .actions
    = f.submit 'Save'

app/views/posts/_post.html.haml
.comment
  %p
    %b= post.name
    = post.created_at
  %p= post.message

app/views/user_sessions/_form.html.haml
= form_for @user_session do |f|
  - if @user_session.errors.any?
    #error_explanation
      %h2= pluralize(@user_session.errors.count, 'error')
      %ul
        - @user_session.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    .field
      = f.label :login
      = f.text_field :login
    .field
      = f.label :password
      = f.password_field :password
    .actions
      = f.submit 'Login'

app/views/user_sessions/new.html.haml
= render 'form'

app/views/users/_form.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  - if (defined? hide_login_field).nil?
    .field
      = f.label :login
      = f.text_field :login
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form', hide_login_field: true

= link_to 'Back', @user

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', root_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.login

#videos
  %h2 Videos
  %table
    %tr
      %th Title
      %th
      %th
    - @user.videos.each do |video|
      %tr
        %td
          = link_to video.title, video
        %td
          = link_to 'Edit', edit_video_path(video) if own_account?
        %td
          = link_to 'Delete', video, method: :delete if own_account?

app/views/videos/_form.html.haml
= form_for @video, html: { multipart: true } do |f|
  -if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    %br
    = f.text_field :title
  .field
    = f.label :description
    %br
    = f.text_area :description, cols: 100, rows: 15
  .field
    = f.label :video
    = f.file_field :video
  .actions
    = f.submit 'Save'

app/views/videos/_video.html.haml
#title
  %h2= video.title
#author
  %p
    %b
      Author:
      = video.user.login
#player
#description
  %p
    %b
      Description:
  %p
    = video.description

:javascript
  jwplayer("player").setup({
    flashplayer: "/player/player.swf",
    file: "#{video.video.url}",
    width: 480,
    height: 360
  });

app/views/videos/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
= link_to('Upload video', new_video_path) if logged_in?

%h1 Video list

- @videos.each do |video|
  %h3= link_to video.title, video
  %p= truncate video.description, lenght: 200

= will_paginate @videos, :param_name => :page

app/views/videos/new.html.haml
%h1 New video

= render 'form'

= link_to 'Back', videos_path

app/views/videos/show.html.haml
%p#notice= notice

#video
  = render @video

#comments
  %b Comments
  = render @video.posts

#comment_form
  = render 'posts/form', video: @video